const {
  SITE_NAME,
  OGP_WORKER,
  OG_IMAGE_URL,
  DESCRIPTION,
  KEYWORDS,
  ANALYTICS_TOKEN,
} = process.env

export { SITE_NAME, OGP_WORKER, OG_IMAGE_URL, DESCRIPTION, KEYWORDS, ANALYTICS_TOKEN }
