name: mirror
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    if: github.repository == 'euxn23/blog-site'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          repositories: "blog-site-mirror"
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git remote add mirror https://github.com/euxn23/blog-site-mirror.git
          git fetch mirror
          git branch -a
          git push mirror maim -f
